export const events = [
  {
    data: [
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_VIEW_SUCCESS',
        uqudo_session_id: 'ca9158c6-548c-43aa-a643-5f536e98f629',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_STEP_UPLOAD_DOCUMENT',
        timestamp: '2025-03-06T10:58:16.574Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'VIEW',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_START_SUCCESS',
        uqudo_session_id: 'ca9158c6-548c-43aa-a643-5f536e98f629',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_LOADING_SCREEN',
        timestamp: '2025-03-06T10:58:23.851Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'START',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_COMPLETE_FAILURE',
        uqudo_session_id: 'ca9158c6-548c-43aa-a643-5f536e98f629',
        status: 'FAILURE',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_STEP_UPLOAD_DOCUMENT',
        timestamp: '2025-03-06T10:58:26.252Z',
        statusCode: 'SCAN_DOCUMENT_NOT_RECOGNIZED',
        statusMessage: 'Document type not recognized',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'COMPLETE',
      },
    ],
    uqudo_session_id: 'ca9158c6-548c-43aa-a643-5f536e98f629',
  },
  {
    data: [
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_VIEW_SUCCESS',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_STEP_UPLOAD_DOCUMENT',
        timestamp: '2025-03-06T10:59:54.727Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'VIEW',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_START_SUCCESS',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_LOADING_SCREEN',
        timestamp: '2025-03-06T11:00:06.892Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'START',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_COMPLETE_SUCCESS',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_LOADING_SCREEN',
        timestamp: '2025-03-06T11:00:09.522Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'COMPLETE',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_VIEW_SUCCESS',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'SUCCESS',
        uqudo_step: 'UQUDO_STEP_FACE_SCAN',
        timestamp: '2025-03-06T11:00:10.797Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'VIEW',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_START_SUCCESS',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'SUCCESS',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:00:12.072Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'START',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:00:12.254Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_DISTANCE_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:00:13.118Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_POSITION_DETECTED',
        page: 'SCAN',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:00:18.095Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_POSITION_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:00:23.078Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_POSITION_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:00:23.900Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_DISTANCE_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:00:29.717Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_POSITION_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:00:34.695Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_DISTANCE_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:00:36.351Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_POSITION_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:00:40.501Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_DISTANCE_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:00:42.153Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_POSITION_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:00:46.319Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_DISTANCE_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:00:47.142Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_POSITION_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_COMPLETE_SUCCESS',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'SUCCESS',
        uqudo_step: 'UQUDO_LOADING_SCREEN',
        timestamp: '2025-03-06T11:00:54.412Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'COMPLETE',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_undefined_PAGE_trigger_FINISH_SUCCESS',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'SUCCESS',
        timestamp: '2025-03-06T11:00:55.021Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'FINISH',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_SUBMITED_FAILED',
        uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
        status: 'FAILURE',
        timestamp: '2025-03-06T11:02:55.021Z',
        statusCode: 'id already exist',
        page: 'FACE',
        event: 'SUBMITED',
      },
    ],
    uqudo_session_id: 'eed5c253-8746-46e6-92de-911f2641bd35',
  },
  {
    data: [
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_VIEW_SUCCESS',
        uqudo_session_id: '814cc38d-70dd-472f-b842-aab05f94cb6e',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_STEP_UPLOAD_DOCUMENT',
        timestamp: '2025-03-04T12:28:41.771Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'VIEW',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_START_SUCCESS',
        uqudo_session_id: '814cc38d-70dd-472f-b842-aab05f94cb6e',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_LOADING_SCREEN',
        timestamp: '2025-03-04T12:28:51.494Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'START',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_COMPLETE_SUCCESS',
        uqudo_session_id: '814cc38d-70dd-472f-b842-aab05f94cb6e',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_LOADING_SCREEN',
        timestamp: '2025-03-04T12:28:53.839Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'COMPLETE',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_VIEW_SUCCESS',
        uqudo_session_id: '814cc38d-70dd-472f-b842-aab05f94cb6e',
        status: 'SUCCESS',
        timestamp: '2025-03-04T12:28:54.337Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'VIEW',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_START_SUCCESS',
        uqudo_session_id: '814cc38d-70dd-472f-b842-aab05f94cb6e',
        status: 'SUCCESS',
        timestamp: '2025-03-04T12:28:56.856Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'START',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: '814cc38d-70dd-472f-b842-aab05f94cb6e',
        status: 'FAILURE',
        timestamp: '2025-03-04T12:28:57.038Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_DISTANCE_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: '814cc38d-70dd-472f-b842-aab05f94cb6e',
        status: 'FAILURE',
        timestamp: '2025-03-04T12:28:58.719Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_POSITION_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_COMPLETE_SUCCESS',
        uqudo_session_id: '814cc38d-70dd-472f-b842-aab05f94cb6e',
        status: 'SUCCESS',
        uqudo_step: 'UQUDO_LOADING_SCREEN',
        timestamp: '2025-03-04T12:29:08.523Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'COMPLETE',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_undefined_PAGE_trigger_FINISH_SUCCESS',
        uqudo_session_id: '814cc38d-70dd-472f-b842-aab05f94cb6e',
        status: 'SUCCESS',
        timestamp: '2025-03-04T12:29:09.069Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'FINISH',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_SUBMITED_FAILED',
        uqudo_session_id: '814cc38d-70dd-472f-b842-aab05f94cb6e',
        timestamp: '2025-03-04T12:29:09.069Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'SUBMIT',
        status: 'FAILURE',
      },
    ],
    uqudo_session_id: '814cc38d-70dd-472f-b842-aab05f94cb6e',
  },
  {
    data: [
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_VIEW_SUCCESS',
        uqudo_session_id: '14256037-9752-4d01-8b40-edeede5860a1',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_STEP_UPLOAD_DOCUMENT',
        timestamp: '2025-03-06T11:02:40.773Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'VIEW',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_START_SUCCESS',
        uqudo_session_id: '14256037-9752-4d01-8b40-edeede5860a1',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_LOADING_SCREEN',
        timestamp: '2025-03-06T11:02:49.033Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'START',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_COMPLETE_FAILURE',
        uqudo_session_id: '14256037-9752-4d01-8b40-edeede5860a1',
        status: 'FAILURE',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_STEP_UPLOAD_DOCUMENT',
        timestamp: '2025-03-06T11:02:52.828Z',
        statusCode: 'SCAN_DOCUMENT_NOT_RECOGNIZED',
        statusMessage: 'Document type not recognized',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'COMPLETE',
      },
    ],
    uqudo_session_id: '14256037-9752-4d01-8b40-edeede5860a1',
  },
  {
    data: [
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_VIEW_SUCCESS',
        uqudo_session_id: '69023e30-8082-4f9d-ba00-d5a52f6dcc13',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_STEP_UPLOAD_DOCUMENT',
        timestamp: '2025-03-06T11:04:33.965Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'VIEW',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_START_SUCCESS',
        uqudo_session_id: '69023e30-8082-4f9d-ba00-d5a52f6dcc13',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_LOADING_SCREEN',
        timestamp: '2025-03-06T11:04:45.155Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'START',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_COMPLETE_SUCCESS',
        uqudo_session_id: '69023e30-8082-4f9d-ba00-d5a52f6dcc13',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_LOADING_SCREEN',
        timestamp: '2025-03-06T11:04:47.469Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'COMPLETE',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_VIEW_SUCCESS',
        uqudo_session_id: '69023e30-8082-4f9d-ba00-d5a52f6dcc13',
        status: 'SUCCESS',
        uqudo_step: 'UQUDO_STEP_FACE_SCAN',
        timestamp: '2025-03-06T11:04:48.744Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'VIEW',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_START_SUCCESS',
        uqudo_session_id: '69023e30-8082-4f9d-ba00-d5a52f6dcc13',
        status: 'SUCCESS',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:04:49.848Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'START',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: '69023e30-8082-4f9d-ba00-d5a52f6dcc13',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:04:50.029Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_POSITION_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_COMPLETE_FAILURE',
        uqudo_session_id: '69023e30-8082-4f9d-ba00-d5a52f6dcc13',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_LOADING_SCREEN',
        timestamp: '2025-03-06T11:04:57.374Z',
        statusCode: 'FACE_NO_MATCH',
        statusMessage: 'Face score 0 is below threshold',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'COMPLETE',
      },
    ],
    uqudo_session_id: '69023e30-8082-4f9d-ba00-d5a52f6dcc13',
  },
  {
    data: [
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_VIEW_SUCCESS',
        uqudo_session_id: 'adbd84a1-5387-4c2a-ae3d-00a29b056dc3',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_STEP_UPLOAD_DOCUMENT',
        timestamp: '2025-03-06T11:06:42.835Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'VIEW',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_START_SUCCESS',
        uqudo_session_id: 'adbd84a1-5387-4c2a-ae3d-00a29b056dc3',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_LOADING_SCREEN',
        timestamp: '2025-03-06T11:06:58.757Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'START',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_SCAN_PAGE_trigger_COMPLETE_SUCCESS',
        uqudo_session_id: 'adbd84a1-5387-4c2a-ae3d-00a29b056dc3',
        status: 'SUCCESS',
        documentType: 'UAE_ID',
        uqudo_step: 'UQUDO_LOADING_SCREEN',
        timestamp: '2025-03-06T11:07:00.756Z',
        category: 'ENROLLMENT',
        page: 'SCAN',
        event: 'COMPLETE',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_VIEW_SUCCESS',
        uqudo_session_id: 'adbd84a1-5387-4c2a-ae3d-00a29b056dc3',
        status: 'SUCCESS',
        uqudo_step: 'UQUDO_STEP_FACE_SCAN',
        timestamp: '2025-03-06T11:07:02.053Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'VIEW',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_START_SUCCESS',
        uqudo_session_id: 'adbd84a1-5387-4c2a-ae3d-00a29b056dc3',
        status: 'SUCCESS',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:07:16.562Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'START',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: 'adbd84a1-5387-4c2a-ae3d-00a29b056dc3',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:07:16.755Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_POSITION_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_IN_PROGRESS_FAILURE',
        uqudo_session_id: 'adbd84a1-5387-4c2a-ae3d-00a29b056dc3',
        status: 'FAILURE',
        uqudo_step: 'UQUDO_STEP_BEFORE_FACE_SCAN',
        timestamp: '2025-03-06T11:07:17.607Z',
        category: 'ENROLLMENT',
        statusCode: 'FACE_INCORRECT_DISTANCE_DETECTED',
        page: 'FACE',
        event: 'IN_PROGRESS',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_FACE_PAGE_trigger_COMPLETE_SUCCESS',
        uqudo_session_id: 'adbd84a1-5387-4c2a-ae3d-00a29b056dc3',
        status: 'SUCCESS',
        uqudo_step: 'UQUDO_LOADING_SCREEN',
        timestamp: '2025-03-06T11:07:28.917Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'COMPLETE',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_UAE_ID_undefined_PAGE_trigger_FINISH_SUCCESS',
        uqudo_session_id: 'adbd84a1-5387-4c2a-ae3d-00a29b056dc3',
        status: 'SUCCESS',
        timestamp: '2025-03-06T11:07:29.357Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'FINISH',
      },
      {
        uqudoEventName: 'idverification_uae__uqudo_SUBMITED_SUCCESS',
        uqudo_session_id: 'adbd84a1-5387-4c2a-ae3d-00a29b056dc3',
        timestamp: '2025-03-06T11:07:29.357Z',
        category: 'ENROLLMENT',
        page: 'FACE',
        event: 'SUBMIT',
        status: 'SUCCESS',
      },
    ],
    uqudo_session_id: 'adbd84a1-5387-4c2a-ae3d-00a29b056dc3',
  },
];
